CREATE TABLE AGENCIAS(
    ID_AGENCIA VARCHAR2(4) PRIMARY KEY,
    NOMBRE VARCHAR2(255),
    PAIS VARCHAR2(255),
    FECHA_FUNDACION VARCHAR2(255),
    sanchezjoel VARCHAR2 (150) NOT NULL
);

CREATE TABLE SATELITES(
    ID_SATELITE VARCHAR2(4) PRIMARY KEY,
    NOMBRE VARCHAR2(255),
    ORBITA VARCHAR2(255),
    PESO NUMBER(255),
    COSTE NUMBER(100,2),
    ACTIVO VARCHAR2(10),
    FECHA_LANZAMIENTO VARCHAR2(255),
    ID_AGENCIA VARCHAR2(4),
    sanchezjoel VARCHAR2 (150) NOT NULL,

    CONSTRAINT ck_ACTIVO CHECK(ACTIVO IN ('TRUE' or 'FALSE')), 
    CONSTRAINT fk_AGENCIA FOREIGN KEY (ID_AGENCIA) REFERENCES AGENCIAS(ID_AGENCIA)
);

CREATE TABLE DETALLES_SATELITE(
    ID_DETALLE VARCHAR2(4) PRIMARY KEY,
    VELOCIDAD_MAXIMA NUMBER(255),
    COMBUSTIBLE NUMBER(255),
    VIDA_UTIL NUMBER(255),
    TEMPERATURA_MAXIMA NUMBER(255),
    ID_SATELITE, VARCHAR2(4) UNIQUE,
    sanchezjoel VARCHAR2 (150) NOT NULL,

    CONSTRAINT fk_SATELITE FOREIGN KEY (ID_SATELITE) REFERENCES SATELITES(ID_SATELITE)
);