--INSRTS DE AGENCIAS

INSERT INTO AGENCIAS(ID_AGENCIA,NOMBRE,PAIS,FECHA_FUNDACION,sanchezjoel
) VALUES(1, 'AGENCIA1', 'ESPAÑA', 1999, 'sanchezjoel');

INSERT INTO AGENCIAS(ID_AGENCIA,NOMBRE,PAIS,FECHA_FUNDACION,sanchezjoel
) VALUES(2, 'AGENCIA2', 'FRANCIA', 1998, 'sanchezjoel');

INSERT INTO AGENCIAS(ID_AGENCIA,NOMBRE,PAIS,FECHA_FUNDACION,sanchezjoel
) VALUES(3, 'AGENCIA3', 'MARRUECOS', 1997, 'sanchezjoel');

INSERT INTO AGENCIAS(ID_AGENCIA,NOMBRE,PAIS,FECHA_FUNDACION,sanchezjoel
) VALUES(4, 'AGENCIA4', 'ALEMANIA', 1996, 'sanchezjoel');

INSERT INTO AGENCIAS(ID_AGENCIA,NOMBRE,PAIS,FECHA_FUNDACION,sanchezjoel
) VALUES(5, 'AGENCIA5', 'ALBANIA', 1995, 'sanchezjoel');

-- INSERTS DE SATELITES

INSERT INTO SATELITES(ID_SATELITE, NOMBRE, ORBITA, PESO, COSTE, ACTIVO, FECHA_LANZAMIENTO, ID_AGENCIA, sanchezjoel
) VALUES(1, 'ALPHA', 'ORBITA1', 8, 50, 'TRUE', '10/1/2000', 'sanchezjoel');

INSERT INTO SATELITES(ID_SATELITE, NOMBRE, ORBITA, PESO, COSTE, ACTIVO, FECHA_LANZAMIENTO, ID_AGENCIA, sanchezjoel
) VALUES(2, 'BETA', 'ORBITA2', 16, 100, 'FALSE', '11/2/2002', 'sanchezjoel');

INSERT INTO SATELITES(ID_SATELITE, NOMBRE, ORBITA, PESO, COSTE, ACTIVO, FECHA_LANZAMIENTO, ID_AGENCIA, sanchezjoel
) VALUES(3, 'CHARLIE', 'ORBITA3', 32, 200, 'TRUE', '12/3/2004', 'sanchezjoel');

INSERT INTO SATELITES(ID_SATELITE, NOMBRE, ORBITA, PESO, COSTE, ACTIVO, FECHA_LANZAMIENTO, ID_AGENCIA, sanchezjoel
) VALUES(1, 'DELTA', 'ORBITA4', 64, 400, 'TRUE', '13/6/2008', 'sanchezjoel');

INSERT INTO SATELITES(ID_SATELITE, NOMBRE, ORBITA, PESO, COSTE, ACTIVO, FECHA_LANZAMIENTO, ID_AGENCIA, sanchezjoel
) VALUES(1, 'ECHO', 'ORBITA5', 128, 800, 'FALSE', '14/1/2016', 'sanchezjoel');


-- INSERTS DE DETALLES

INSERT INTO DETALLES(ID_SATELITE, VELOCIDAD_MAXIMA, COMBUSTIBLE, VIDA_UTIL, TEMPERATURA_MAXIMA, ID_SATELITE, sanchezjoel
) VALUES(1, 500, 500, 10, 200, 1, 'sanchezjoel');

INSERT INTO DETALLES(ID_SATELITE, VELOCIDAD_MAXIMA, COMBUSTIBLE, VIDA_UTIL, TEMPERATURA_MAXIMA, ID_SATELITE, sanchezjoel
) VALUES(2, 500, 500, 20, 300, 2, 'sanchezjoel');

INSERT INTO DETALLES(ID_SATELITE, VELOCIDAD_MAXIMA, COMBUSTIBLE, VIDA_UTIL, TEMPERATURA_MAXIMA, ID_SATELITE, sanchezjoel
) VALUES(3, 1000, 1000, 10, 200, 3, 'sanchezjoel');

INSERT INTO DETALLES(ID_SATELITE, VELOCIDAD_MAXIMA, COMBUSTIBLE, VIDA_UTIL, TEMPERATURA_MAXIMA, ID_SATELITE, sanchezjoel
) VALUES(4, 1000, 500, 20, 200, 4, 'sanchezjoel');

INSERT INTO DETALLES(ID_SATELITE, VELOCIDAD_MAXIMA, COMBUSTIBLE, VIDA_UTIL, TEMPERATURA_MAXIMA, ID_SATELITE, sanchezjoel
) VALUES(5, 1000, 100, 30, 300, 5, 'sanchezjoel');